title: Stockton Rebels Softball
email: stocktonrebels@gmail.com
description: Stockton Rebels Girls Softball
baseurl: "" 
url: "http://stocktonrebels.info"
twitter_username: RebelsStockton
github_username:  stockton-rebels

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
